models:
  deepseek-r1:
    platform_name: groq
    temperature: 0.7
    top_p: 0.9
    n: 1
    max_tokens: 6000
    model_type: deepseek-r1-distill-llama-70b
  llama-70b:
    platform_name: groq
    temperature: 0.7
    top_p: 0.9
    n: 1
    max_tokens: 6000
    model_type: llama-3.3-70b-specdec
  gpt-4o-mini:
    temperature: 0.0
    top_p: 0.9
    n: 1
    max_tokens: 10000
  o3-mini:
    temperature: 0.0
    top_p: 0.9
    n: 1
    max_tokens: 10000